### ISSUE TITLE
glfw not found in vendor folder for darwin

### ISSUE THREAD

**Issue by 2mol** [mkeeter/erizo#2]
Hi there! Very cool project, I was excited to try and get it to run on my mac.

Both `make` and `./deploy.sh` into the issue that there is no `vendor/glfw/build-darwin/src` folder.

In can look into this more closely later in the week, but I thought I'd already open an issue in case I'm missing something obvious.

I should also say that I'm on an M1 mac, so feel free to let me know if that might not work out anyway.

Cheers!

**Comment by peanball** [comment]
Before calling the deploy script, you need to also build the bundled glfw via:
```
make glfw
```

**Comment by mkeeter** [comment]
Thanks, added to `deploy.sh` in 7133649ac62b486c42425185e42ad3b7e120630c

**Comment by 2mol** [comment]
super, that did the job, thanks :)
