### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by snshn** [mkeeter/erizo#5]
Currently there's no license associated with the project. Using something like MIT or GPLv3 could make it much easier to package the app up and distribute via Snap store or distributions' repositories.

**Comment by mkeeter** [comment]
Good point!  I see that you've contributed some code in PRs – are you okay with dual licensing MIT/Apache?

**Comment by snshn** [comment]
Yessir, whatever you think it should be, please go for it, it's your baby! 👍🏻
